#!/bin/sh

# Number of copies
ncop=$1

# Makes 'ncop' copies of each image, like this for 'ncop=3':
#    cp img000.ppm  tmptmp/img000.ppm
#    cp img000.ppm  tmptmp/img001.ppm
#    cp img000.ppm  tmptmp/img002.ppm
#    cp img001.ppm  tmptmp/img003.ppm
#    cp img001.ppm  tmptmp/img004.ppm
#    cp img001.ppm  tmptmp/img005.ppm
#          ...

# Step 1:  Create temporary directory if necessary
if test -d tmptmp
then
	rm -f tmptmp/*
else
	mkdir tmptmp
fi

# Step 2:  Copy files
basename="img"
i=0
until test $i = 501
do
	fnamein=`printf "$basename%03d.ppm" $i`
	echo $fnamein
	k=0
	until test $k = $ncop
	do
		j=`expr $ncop \* $i + $k`
		fnameout=`printf "tmptmp/$basename%03d.ppm" $j`
		echo $fnameout
		cp $fnamein $fnameout
		k=`expr 1 + $k`
	done
	i=`expr 1 + $i`
done

chmod u+w tmptmp/*[0-4].ppm
chmod u+w tmptmp/*[5-9].ppm
