#!/bin/sh

# Makes three copies of each image, like this:
#    cp img000.ppm  tmptmp/img000.ppm
#    cp img000.ppm  tmptmp/img001.ppm
#    cp img000.ppm  tmptmp/img002.ppm
#    cp img001.ppm  tmptmp/img003.ppm
#    cp img001.ppm  tmptmp/img004.ppm
#    cp img001.ppm  tmptmp/img005.ppm
#          ...

# Step 1:  Create temporary directory if necessary
if test ! -d tmptmp
then
	mkdir tmptmp
fi

# Step 2:  Copy files
basename="img"
i=0
until test $i = 0
do
	fnamein=`printf "$basename%03d.ppm" $i`
	echo $fnamein
	j=`expr 3 \* $i + 0`
	fnameout=`printf "tmptmp/$basename%03d.ppm" $j`
	echo $fnameout
	cp $fnamein $fnameout
	j=`expr 3 \* $i + 1`
	fnameout=`printf "tmptmp/$basename%03d.ppm" $j`
	echo $fnameout
	cp $fnamein $fnameout
	j=`expr 3 \* $i + 2`
	fnameout=`printf "tmptmp/$basename%03d.ppm" $j`
	echo $fnameout
	cp $fnamein $fnameout
	i=`expr 1 + $i`
done

